### ISSUE TITLE
vscode type hint error message on default values

### ISSUE THREAD

**Issue by waptik** [oliver-oloughlin/kvdex#101]
It'd be helpful if kvdex can stop showing type hint error message when default values for new entries are not set. Currently, vscode is throwing some type hint error when using `.add()` without adding values to default fields. The entries are being created alright but it's just the type hint error message that's getting in the way

Here's my db schema definition:
```ts
// models
const withDefautTimestamps = z.object({
	created_at: z
		.string()
		.datetime()
		.default(() => new Date().toISOString()),
	updated_at: z
		.string()
		.datetime()
		.default(() => new Date().toISOString()),
});

export type User = z.infer<typeof UserModel>

export const UserModel = z.object({
	userId: z.number().describe('unique'),
	credits: z.number().default(3)
}).merge(withDefautTimestamps)

// db defintion
import { 
    kvdex,
    model,
    collection, 
    indexableCollection,
  } from "https://deno.land/x/kvdex@v0.19.2/mod.ts"
  import { UserModel } from '$db/models.ts';
  import { ulid } from "ulid";
  
  const kv = await Deno.openKv()
  
  export const db = kvdex(kv, {
   users: indexableCollection(UserModel, {
      indices: {
        userId: "primary", // unique
      },
      idGenerator: () => ulid()
    }),
  })
```

Here's the error shown by vscode when you hover over it:
```sh
Argument of type '{ userId: number; }' is not assignable to parameter of type '{ userId: number; credits: number; created_at: string; updated_at: string; }'.
  Type '{ userId: number; }' is missing the following properties from type '{ userId: number; credits: number; created_at: string; updated_at: string; }': credits, created_at, updated_atdeno-ts(2345)
```

**Comment by oliver-oloughlin** [comment]
I understand the issue, but I'm not sure how a "fix" should be implemented in this case.
This is more or less due to the specific nature of Zod, where it will fill in a missing field when there is a default value. I would like to avoid implementing behaviors that are specific to Zod, which would make it a dependency and ruin the idea of being model-agnostic.

I'll do some testing and see if I can come up with any good solutions. Right now I have an idea of how to "disable" the type enforcement at will using a generic type, so I'll explore that for a bit and then come back to you.

**Comment by oliver-oloughlin** [comment]
Hey, I just released a new update which includes a fix for this issue.
You should now be able to get correctly inferred insert types by using the new zodModel() extension:

```ts
// models
const withDefautTimestamps = z.object({
	created_at: z
		.string()
		.datetime()
		.default(() => new Date().toISOString()),
	updated_at: z
		.string()
		.datetime()
		.default(() => new Date().toISOString()),
});

export type User = z.infer<typeof UserModel>

export const UserModel = z.object({
	userId: z.number().describe('unique'),
	credits: z.number().default(3)
}).merge(withDefautTimestamps)

// db defintion
import { 
    kvdex,
    model,
    collection, 
    indexableCollection,
  } from "https://deno.land/x/kvdex@v0.19.3/mod.ts"
import { UserModel } from '$db/models.ts';
import { ulid } from "ulid";
import { zodModel } from "https://deno.land/x/kvdex@v0.19.3/ext/zod.ts"
  
  const kv = await Deno.openKv()
  
  export const db = kvdex(kv, {
   users: indexableCollection(zodModel(UserModel), {
      indices: {
        userId: "primary", // unique
      },
      idGenerator: () => ulid()
    }),
  })
```

I have also updated the README with an example. Please let me know if this still doesn't fix your issue.

**Comment by waptik** [comment]
> Hey, I just released a new update which includes a fix for this issue. You should now be able to get correctly inferred insert types by using the new zodModel() extension:
> 
> ```ts
> // models
> const withDefautTimestamps = z.object({
> 	created_at: z
> 		.string()
> 		.datetime()
> 		.default(() => new Date().toISOString()),
> 	updated_at: z
> 		.string()
> 		.datetime()
> 		.default(() => new Date().toISOString()),
> });
> 
> export type User = z.infer<typeof UserModel>
> 
> export const UserModel = z.object({
> 	userId: z.number().describe('unique'),
> 	credits: z.number().default(3)
> }).merge(withDefautTimestamps)
> 
> // db defintion
> import { 
>     kvdex,
>     model,
>     collection, 
>     indexableCollection,
>   } from "https://deno.land/x/kvdex@v0.19.6/mod.ts"
> import { UserModel } from '$db/models.ts';
> import { ulid } from "ulid";
> import { zodModel } from "https://deno.land/x/kvdex@v0.19.6/ext/zod.ts"
>   
>   const kv = await Deno.openKv()
>   
>   export const db = kvdex(kv, {
>    users: indexableCollection(zodModel(UserModel), {
>       indices: {
>         userId: "primary", // unique
>       },
>       idGenerator: () => ulid()
>     }),
>   })
> ```
> 
> I have also updated the README with an example. Please let me know if this still doesn't fix your issue.

Thanks for the updates. I used the latest version of kvdex on the project and it works. I no longer need to manually add default values again.
