### ISSUE TITLE
No type definition for document id in CommitResult object for .add()

### ISSUE THREAD

**Issue by waptik** [oliver-oloughlin/kvdex#102]
I'm trying kvdex for the first time, and i came across the new bug. According to the [`.add()` docs](https://deno.land/x/kvdex@v0.18.4#add), **a CommitResult object will be returned with the document id, versionstamp and ok flag upon completion** which is correct but there's not a type definition for that. My db definition can be found in #101 
![image](https://github.com/oliver-oloughlin/kvdex/assets/1687551/bf7c4e88-fbd5-40fd-af46-7cfdd94a5d82)

**Comment by oliver-oloughlin** [comment]
I see what's going on here, maybe I could have worded it better and should probably update the examples.
 
The add method, alongside other similar methods, can return either a commit result or a commit error. A commit error will be { ok: false } and not contain an id or versionstamp. Therefore for TypeScript to infer the result as a successful CommitResult, you need to make a check on the ok flag first.

```ts
const user = await db.users.add(...)

if (!user.ok) {
  // Handle error case
  return
}

// After asserting that the result is successful the type is inferred correctly
const id = user.id
```
