### ISSUE TITLE
DENO_CORE.serialize bug on Deno Deploy?

### ISSUE THREAD

**Issue by juliendorra** [oliver-oloughlin/kvdex#130]
My code is working on local, but when deployed on Deno Deploy, it throws the following error: 

```
TypeError: DENO_CORE.serialize is not a function
    at Object.serialize (https://deno.land/x/kvdex@v0.23.1/src/utils.ts:564:20)
    at Collection.setDoc (https://deno.land/x/kvdex@v0.23.1/src/collection.ts:1402:46)
    at Collection.setDocument (https://deno.land/x/kvdex@v0.23.1/src/collection.ts:1369:23)
    at Collection.add (https://deno.land/x/kvdex@v0.23.1/src/collection.ts:396:23)
    at storeGroups (file:///src/kv-storage.ts:41:34)
    at Server.handler (file:///src/main.ts:53:11)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Server.#respond (https://deno.land/std@0.208.0/http/server.ts:313:18)
```

Could it be related to this: https://github.com/denoland/deno/issues/12379 ?

Note: I'm using 

```
const db = kvdex(kv, {
    apps: collection(GroupsModel, {
        indices: {
            urlid: "secondary",
            timestamp: "secondary",
        },
        serialized: true,
        idGenerator: () => ulid()
    })
});

```
To define my collection.

**Comment by juliendorra** [comment]
Thanks again for the super fast answer, even if it's not good news 😂

I had briefly checked https://github.com/phaux/kvfs before kvdex, and its chunk algorithm may be ok for kvdex? (I didn't evaluate it all, I don't know if it's actually good or bad!)

Is that what you mean by non-third party? Purely written in JS?

Is there anything I have to know about the serialize / deserialize function to pass? Any limitation or constraint to respect?

**Comment by oliver-oloughlin** [comment]
By non-third party I mean something native to Deno, that doesn't introduce any dependencies outside of Deno API's, Deno std or built-in node APIs. I'll check out kvfs and see what they have done, thanks for pointing me to it.

**Comment by oliver-oloughlin** [comment]
After a quick look it seems like kvfs just saves Uint8Array data as chunks, which I already do in kvdex. That's not really the issue. The problem that needs solving is being able to take any JavaScript object and serialize it as a Uint8Array, and to do the opposite when deserializing.

**Comment by juliendorra** [comment]
What about:

```
function serializeObject(obj) {
    const jsonString = JSON.stringify(obj);
    const utf8Encoder = new TextEncoder();
    const uint8Array = utf8Encoder.encode(jsonString);
    return uint8Array;
}

and 

function deserializeUint8Array(uint8Array) {
    const utf8Decoder = new TextDecoder();
    const jsonString = utf8Decoder.decode(uint8Array);
    const obj = JSON.parse(jsonString);
    return obj;
}
```

I used a similar approach in my app to persist data in the URL fragment (don't do that at home 😅😂)

What would be the downside? JSON.stringify has limitations but that should be acceptable?

**Comment by juliendorra** [comment]
Or would https://deno.land/x/superserial works?

**Comment by juliendorra** [comment]
Enabling your custom function with a flag would be useful! In the meantime maybe an alert in the readme that serialize won't work as-is on Deno Deploy would be useful for others that might work on local and be surprised when deploying (as Deno Deploy is the go-to deploy option of the ecosystem)

I'll test using Superserial and see if it could be a recommendation for other devs

**Comment by oliver-oloughlin** [comment]
Thanks, your raised issues have helped me a lot in discovering potential bug/problems in kvdex and trying to fix them.

**Comment by juliendorra** [comment]
I must be missing something, as I just tried to test using superserial and it seems the custom functions are not used. After adding this:

```

import { Serializer } from "https://deno.land/x/superserial/mod.ts";

const serializer = new Serializer();

// Setting up the database with collections
const db = kvdex(kv, {
    apps: collection(GroupsModel, {
        indices: {
            urlid: "secondary",
            timestamp: "secondary",
        },
        serialized: {
            serialize: serializer.serialize,
            deserialize: serializer.deserialize,
        },
        idGenerator: () => ulid()
    })
});

```

The code still is bugging on Deploy and is still passing by the same spot:

`    TypeError: DENO_CORE.serialize is not a function
    at serialize (https://deno.land/x/kvdex@v0.23.1/src/utils.ts:564:20)
    at https://deno.land/x/kvdex@v0.23.1/src/utils.ts:170:24
    at Array.forEach (<anonymous>)
    at setIndices (https://deno.land/x/kvdex@v0.23.1/src/utils.ts:164:34)
    at Collection.setDoc (https://deno.land/x/kvdex@v0.23.1/src/collection.ts:1428:7)
    at Collection.setDocument (https://deno.land/x/kvdex@v0.23.1/src/collection.ts:1369:23)
    at Collection.add (https://deno.land/x/kvdex@v0.23.1/src/collection.ts:396:23)
    at storeGroups (file:///src/kv-storage.ts:47:34)
    at Server.handler (file:///src/main.ts:53:11)
    at eventLoopTick (ext:core/01_core.js:183:11)
`

As if it was ignoring my custom functions.

What do I miss here?

**Comment by oliver-oloughlin** [comment]
Yep, I've just found a big issue on my part: Indices use the Core serializer no matter what custom serilaizer is used. I have a branch where Im working on solving all of this, should be fixed very soon. My current idea is to detect if the application is running on Deploy or not and set the default serializer based on this. I've also changed all parts of the code to always use the collection's set serilaizer.

**Comment by oliver-oloughlin** [comment]
I have a potentially working solution now. Would you be so kind to see if importing from this branch directly fixes all the issues you are seeing? Like so:
```ts
import { kvdex, collection, model } from "https://raw.githubusercontent.com/oliver-oloughlin/kvdex/patch/deploy-compatible-serialize/mod.ts"
```

**Comment by juliendorra** [comment]
I'm happy that I could help found this issue! 

As for the detection, I'd personally rather have the exact same code path for serialization on local and prod, including for example for cloning the prod KV (there's tools that automate that) and testing with it locally.

But the main reason I guess is that I'd rather have a simple, declarative way of setting it instead of magic!

**Comment by oliver-oloughlin** [comment]
Yeah that's a very fair point. I might end up setting the slower json serializer as default. It pains me to give up so much performance as the standard, but it might just be worth it to have a uniform working solution for the normal Deno runtime and Deploy

**Comment by juliendorra** [comment]
> I have a potentially working solution now. Would you be so kind to see if importing from this branch directly fixes all the issues you are seeing? Like so:
> 
> ```ts
> import { kvdex, collection, model } from "https://raw.githubusercontent.com/oliver-oloughlin/kvdex/patch/deploy-compatible-serialize/mod.ts"
> ```

Yes it works! 🙏 🥳

**Comment by oliver-oloughlin** [comment]
Just for comparison, here are the benchmark results for the json serializer and core serializer (roughly 115MB when serialized):
<img width="924" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/54100972/a5471c0d-7116-4edf-8f47-05097a32c1a9">
<img width="910" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/54100972/89c39e46-49fe-433c-aec5-27f15d635446">

**Comment by oliver-oloughlin** [comment]
I might actually go for a compromise solution:
- serialized = true => uses deno core by default (json when on deploy)
- serialized = "core" => always use core
- serialized = "json" => always use json
- serialized = object => use whatever serialize/deserialize/compress/decompress functions that are provided

**Comment by oliver-oloughlin** [comment]
I have released a new version (v0.24.0) with the discussed changes (+ a few more smaller changes). Serialized collections should now work by default on Deploy, and be configurable between using the default chosen serializer, core, json or custom.

**Comment by juliendorra** [comment]
> I might actually go for a compromise solution:
> 
> * serialize = true => uses deno core by default (json when on deploy)
> * serialize = "core" => always use core
> * serialize = "json" => always use json
> * serialize = object => use whatever serialize/deserialize/compress/decompress functions that are provided

I'm still biased against a magic switch on Deploy, as it will have surprising effects for devs. It would be more consistent and as easy to always be explicit ie. deprecate the boolean

**Comment by juliendorra** [comment]
> Just for comparison, here are the benchmark results for the json serializer and core serializer (roughly 58MB when serialized):

What would be the right way to benchmark superserial against these two?

By the way, I ended up using these basic json one-liners, as in my case I only handle pure json anyway (as it's data coming and going to the front):

```
      serialized: {
            serialize: (obj) => new TextEncoder().encode(JSON.stringify(obj)),
            deserialize: (data) => JSON.parse(new TextDecoder().decode(data)),
        },
```

I guess that they should be faster that your more complex enhanced json serializer?

**Comment by oliver-oloughlin** [comment]
> > I might actually go for a compromise solution:
> > 
> > * serialize = true => uses deno core by default (json when on deploy)
> > * serialize = "core" => always use core
> > * serialize = "json" => always use json
> > * serialize = object => use whatever serialize/deserialize/compress/decompress functions that are provided
> 
> I'm still biased against a magic switch on Deploy, as it will have surprising effects for devs. It would be more consistent and as easy to always be explicit ie. deprecate the boolean.
> 
> Replace the true boolean by a "auto" option and I think it would be just perfect!

I like the suggestion of replacing true with "auto", I think I will make this change.

**Comment by oliver-oloughlin** [comment]
> > Just for comparison, here are the benchmark results for the json serializer and core serializer (roughly 58MB when serialized):
> 
> What would be the right way to benchmark superserial against these two?
> 
> By the way, I ended up using these basic json one-liners, as in my case I only handle pure json anyway (as it's data coming and going to the front):
> 
> ```
>       serialized: {
>             serialize: (obj) => new TextEncoder().encode(JSON.stringify(obj)),
>             deserialize: (data) => JSON.parse(new TextDecoder().decode(data)),
>         },
> ```
> 
> I guess that they should be faster that your more complex enhanced json serializer?

It will definitely be faster than my custom json stringify/parse as it handles checks for every possible KvValue type. But I think it will still be way slower than a lot of other methods, like v8's serialize (which is what Deno core uses), that serializes to Uint8Array. If you just have JSON data anyway, and it's not ridiculously large (many 10s or even 100s of MB), I think you'll be fine, the speed difference won't be too noticeable. In a previous version of kvdex I used the basic JSON.parse/stringify for large objects, and I was using it in another project where I had data that reached about 150kB, and writing/reading was still done in just a few ms (roughly 5-15ms).

**Comment by oliver-oloughlin** [comment]
> What would be the right way to benchmark superserial against these two?

You can check out the benchmarks I made here: https://github.com/oliver-oloughlin/kvdex/tree/main/benchmarks/utils
