### ISSUE TITLE
How to do upsert?

### ISSUE THREAD

**Issue by halvardssm** [oliver-oloughlin/kvdex#137]
Hi! I was wondering if you have an example of doing upsert ([prisma style](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#upsert)) using kvdex?

**Comment by oliver-oloughlin** [comment]
There really isn't an exact example of upsert. The closest you would get is the `write()` or `updateMany()`, `updateByPrimaryIndex()` and `updateBySecondaryIndex()` methods. `write()` will set a new document entry if no document with the given id exists, or replace the value of an existing document, while the `update...` methods will only update the value of existing documents (with either full or partial updated values), by id or by an index. None of these truly do the same as upsert, as upsert (from my understanding) could set a new entry not just by id but by any value.

Example of `write()`:
```ts
import { model, collection, kvdex } from "kvdex"
const kv = await Deno.openKv()
const db = kvdex(kv, {
  users: collection(model<User>()),
})

// Before any existing document by id is set, this creates a new entry
await db.users.write("user_id", {
  ...user values
})

// Next query update the existing entry with a new value
await db.users.write("user_id", {
  ...other user values
})
```

The `update...` methods exclusively work on existing documents, so they don't really fit within the scope of upsert.

You could possibly accomplish an upsert-ish type of operation doing the following:
```ts
const { result } = await db.users.getMany({ filter: (doc) => <some `where`equivalent predecate> })

if (result.length > 0) {
  for (cost doc of result) {
    await db.update(doc.id, <new value>)
  }
} else {
  await db.users.add(<new value>)
}
```

None of these really provide the same or equal simplicity to upsert.
It's an interesting question though, I might work on supporting it.
I've never had a use case for using it myself, but it obviously exists for a reason.

**Comment by halvardssm** [comment]
@oliver-oloughlin Thanks for getting back to me! My observations were also the same in this regard. 

> as upsert (from my understanding) could set a new entry not just by id but by any value.

I am not sure about that, an upsert should only be possible to do on unique indexes. Otherwise, it would just be an "add" no? Upsert in its base form (taking Postgres as an example) is a `CREATE` with a `ON CONFLICT ... DO ...`. 

I think a simple wrapper could be easy to implement by using the KV built-ins (2 operations at max). Of course my example underneath doesn't take into account every case, but it is just as a thought as to how it can be achieved.

simplified example:

```ts
function upsert({
  create,
  update,
  key,
}){
  const existingEntry = await kv.get(key)
  if(existing.versionstamp === null){
    return await kv.set(key, create)
  } else {
    return await kv.set(key, { ...existingEntry, ...update })
  }
}
```

> It's an interesting question though, I might work on supporting it.
> I've never had a use case for using it myself, but it obviously exists for a reason.

Would be great to get support for it! I would create a PR if I would have some more time on my hands, but maybe I'll find it one of the days!

**Comment by oliver-oloughlin** [comment]
I have added support for upsert in the latest release (v0.27.0).

I hope this helps or fits what you had in mind. Note that the signature of the method is a little different to what you would expect from Prisma, as I wanted to keep the semantics in line with the rest of the API (e.g. "set" instead of "create", and "id" or "index"). You can find an example in the README.
