### ISSUE TITLE
Unable to deploy to Deno Deploy

### ISSUE THREAD

**Issue by mauritslourens** [oliver-oloughlin/kvdex#171]
When trying to deploy to Deno Deploy using a manual deployment with deployctl or using the github action, I get this error message: "The deployment failed: error sending request for url (https://registry-staging.deno.com/@std/collections/meta.json): error trying to connect: dns error: failed to lookup address information: Name or service not known". I am using the latest version:
```
import {
  kvdex,
  model,
  collection,
} from 'https://deno.land/x/kvdex@0.33.1/mod.ts';
```
using Deno 1.40.4

**Comment by oliver-oloughlin** [comment]
Seems to be because of the jsr imports. Im not sure Deploy supports JSR yet, but Deno does. Have you tried importing from "jsr:@olli/kvdex" instead?

Could also be that jsr and deno.land/x dont play that well together. Will look into it.

**Comment by mauritslourens** [comment]
Thanks for your quick response. First I tried importing from jsr directly, but that didn't work, so I switched to deno.land/x. Locally it works fine, but just not on Deno Deploy. I could give another Deno hosting solution a go, using a Docker container in the meantime.

**Comment by oliver-oloughlin** [comment]
Docker would probably work, anything running the actual Deno runtime should work. As Deploy is a separate runtime, it does often lag a bit behind Deno in getting new features. After some testing in the playground, I cant get any jsr imports to work. So my guess is that Deploy simply hasn't been updated to support jsr yet, but probably will in the near future (unless it's like with npm imports, where it took a long time for Deploy to support it).

**Comment by RickeyWard** [comment]
Related, I can't use JSR imports at all. it used to work locally as long as I imported from denoland, but now (and I don't know what changed) it doesn't work at all. JSR and Deno Fresh aren't friends.

```
Error: Build failed with 3 errors:
https://deno.land/x/kvdex@0.34.0/src/deps.ts:5:7: ERROR: [plugin: deno-resolver] Could not resolve "@std/collections@0.214.0/deep_merge"
https://deno.land/x/kvdex@0.34.0/src/deps.ts:6:23: ERROR: [plugin: deno-resolver] Could not resolve "@std/bytes@0.214.0/concat"
https://deno.land/x/kvdex@0.34.0/src/deps.ts:7:21: ERROR: [plugin: deno-resolver] Could not resolve "@std/ulid@0.214.0"
```
![image](https://github.com/oliver-oloughlin/kvdex/assets/342468/93dbeb6f-3e9f-4d0d-950b-7547c37394bc)

**Comment by juliendorra** [comment]
I had a similar issue and had to pin kvdex to v0.31.2 for anything to deploy to Deno Deploy.

Would love a fix!

**Comment by oliver-oloughlin** [comment]
It seems I may have been a bit premature with moving to JSR if it's this broken for everyone. Do these issues only happen when deployed, or locally as well when using the latest version of Deno (1.40.5)?

**Comment by RickeyWard** [comment]
Possibly related I think the Deno infrastructure might be having some issues. I got an out of memory error on denoland looking at some docs.

My issue was specifically related to Deno-Fresh I can't say for sure it's the same issue others are having.

**Comment by oliver-oloughlin** [comment]
From my testing it seems that Deno Deploy now supports JSR imports, which should allow new versions of kvdex to be imported successfully. Would you @mauritslourens or anyone else be able to confirm that their use case on Deploy works so that we can conclude this issue?

**Comment by oliver-oloughlin** [comment]
@mauritslourens In that example it states that it is using Deno version 1.0.0, that is a very outdated version of Deno, which definitely does not support JSR. This issue is for Deno Deploy, so I was looking to see if that specific use case was fixed for you or not.

**Comment by mauritslourens** [comment]
As you can see on the screenshot I use the latest Deno version when trying to deploy using the latest denoctl:
![Screenshot_20240224-165057.png](https://github.com/oliver-oloughlin/kvdex/assets/138454191/86153311-caaf-4811-9313-2eadab99f68a)

**Comment by oliver-oloughlin** [comment]
Ah I understand. But version 0.34.2 is broken when imported from deno.land/x (it was never meant to be published there). Does importing from JSR work? E.g. `import { ... } from jsr:@olli/kvdex`

**Comment by mauritslourens** [comment]
the latest version (0.43.3) does work now, thanks!
