### ISSUE TITLE
The limit parameter error

### ISSUE THREAD

**Issue by hwcwy** [oliver-oloughlin/kvdex#173]
The limit parameter error restricts the number of items in the filtering process rather than the number of results returned.

```typescript
import {
  collection,
  kvdex,
  model,
} from "https://deno.land/x/kvdex@0.34.0/mod.ts";

type test = {
  a: number;
};

const kv = await Deno.openKv("test");

const db = kvdex(kv, {
  test: collection(model<test>()),
});

await db.wipe();

for (let i = 1; i <= 100; i++) {
  await db.test.add({ a: i });
}

const res = await db.test.getMany({
  limit: 10,
  filter(v) {
    return v.value.a > 50;
  },
});

console.log(res.result); // It will return []

```

**Comment by oliver-oloughlin** [comment]
This is the expected behaviour, when used without offset the `limit` option directly mimicks the use of limit with kv.list. It's not a limit of results, but of how many items are first pulled from the database.

**Comment by hwcwy** [comment]
Got it, thank you for your contribution to this library😊
