### ISSUE TITLE
[history] listing deleted documents when history is active?

### ISSUE THREAD

**Issue by juliendorra** [oliver-oloughlin/kvdex#180]
Hi!

What would be the best way to list deleted documents when using history? Use case: an end user delete several documents, but at some point wish to recover one (ie. retrieve the version just before the delete entry and use that as a new write entry in history).

Is there a simple way to do that with the current API, without knowing the exacts IDs of the deleted documents, but for example only a secondary key?

I couldn't identify a clean way, given the current way history clones and direct documents coexist, but maybe I'm missing something!

**Comment by oliver-oloughlin** [comment]
And note that it might be tempting to also give the option `limit: 1` to increase performance, but don't do this, because it limits the number of values drawn from the database BEFORE other options such as filter are applied, meaning it is not a limit of final results, but of database reads.

**Comment by juliendorra** [comment]
Thanks, this is a very useful recap!

But in my case, I want to list all deleted documents from an user (secondary key) and I don’t know the document ids.

As the documents are deleted, they shouldn’t appear in a find many by secondary index retrieval, and the history itself isn’t searchable by secondary. So it seems the only way is to keep an additional list of all documents IDs created by an user?

**Comment by oliver-oloughlin** [comment]
Ah, I see what you mean now. Yes, you will have to know the the document id somehow. There really isn't any way around that as using indices is completely dependent on the document value, which is not consistent when it comes to version history entries.

**Comment by oliver-oloughlin** [comment]
Closing this issue as it technically has an answer and this behaviour will likely not change: You need to know the id of the document to version history, even for deleted documents. You could store the ids somehow, for example directly in the usee object as an array of deleted document ids, or in a relational manner in separate collection linking a document id with a user id.
