### ISSUE TITLE
Node support

### ISSUE THREAD

**Issue by RuiNtD** [oliver-oloughlin/kvdex#186]
It would be nice if kvdex had support for node, which can use both JSR and Deno KV (via [`npm:@deno/kv`](https://www.npmjs.com/package/@deno/kv)).

**Comment by oliver-oloughlin** [comment]
Definitely something I want to support in the future, but unfortunately seems to be impossible currently for the same reasons as mentioned in #185

**Comment by oliver-oloughlin** [comment]
This should now have been fixed as of #205 and release 1.0.0
