### ISSUE TITLE
types not accessible in v0.34.5

### ISSUE THREAD

**Issue by waptik** [oliver-oloughlin/kvdex#187]
In the latest version, v0.34.5, kvdex returns `any` and the types defined in `types.ts` don't exist when you try to import them.
<img width="618" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/1687551/9a52d0d8-892e-4ca5-a7d4-6d0a8db5e5e7">
<img width="847" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/1687551/892a34e3-ba16-44fc-a5bb-908b0bf55461">

But in v0.34.2, everything works fine
<img width="591" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/1687551/a6bd935f-4ee6-45d1-b297-76f9e19c63ca">
<img width="347" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/1687551/968ca927-97c1-4142-902a-bd4c74f532ef">

**Comment by oliver-oloughlin** [comment]
Seems to be because of the missing lock file. I thought they had fixed this since it started working locally, but apparently not. I will add a lock file again and hopefully this should fix the lsp issue.

**Comment by oliver-oloughlin** [comment]
Importing from deno.land/x should work instead. I have now also released a new version (0.35.0) which should address this issue when importing from jsr. Also make sure you are using the latest version of Deno.

**Comment by waptik** [comment]
Thanks, It's working now. I'm using `v0.35.2` and it's working. Also, my Deno version is` v1.41.1` since early this week so i'm using the latest version of Deno
