### ISSUE TITLE
Relative import path "@olli/kvdex/ext/zod" not prefixed with.... on deno deploy

### ISSUE THREAD

**Issue by waptik** [oliver-oloughlin/kvdex#194]
Is this a deno deploy bug because it works perfectly locally? If it is, i will open an issue about in their feedback repo and ping the discord channel.
I even committed `deno.lock` file to git and the issue still persisted.
I'll give `jsr:@olli/kvdex/ext/zod` a try after this and see how it goes

<img width="621" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/1687551/a2eae347-416d-4cb4-b288-1e7df23b1080">
<img width="421" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/1687551/408c776f-af6d-4b67-b405-ed042f269ea5">
<img width="373" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/1687551/1bd06603-422e-4a4d-b07b-78dd91ebf2d9">

**Comment by waptik** [comment]
So using `jsr:@olli/kvdex/ext/zod` works instead of `@olli/kvdex/ext/zod` which is weird. I think it's a deno deploy bug.
I'm reporting the issue there as well

**Comment by oliver-oloughlin** [comment]
Thats very strange, I think it might be a bug on Deploy when importing package modules then. But I will have to check as well.

**Comment by oliver-oloughlin** [comment]
Wait, I read your issue wrong the first time. You have to use the jsr: specifier when importing from JSR. So that's not weird at all, and it's not an issue.

**Comment by oliver-oloughlin** [comment]
I think it could be that the import map doesn't do what you expect it to.
You would maybe have to add a separate entry for `"@olli/kvdex/ext/zod": "jsr:@olli/kvdex@^0.35.2/ext/zod"`

**Comment by waptik** [comment]
> I think it could be that the import map doesn't do what you expect it to. You would maybe have to add a separate entry for `"@olli/kvdex/ext/zod": "jsr:@olli/kvdex@^0.35.2/ext/zod"`

[Done](https://github.com/waptik/weak-squirrel-86/commit/558e53ff9b77b8ad6bd690544819c4078efc2792). Thanks
I thought [this update](https://deno.com/blog/v1.40#simpler-imports-in-denojson) fixed it! Probably didn't take into account jsr modules at that time
