### ISSUE TITLE
async idGenerator

### ISSUE THREAD

**Issue by ryanleecode** [oliver-oloughlin/kvdex#196]
### Discussed in https://github.com/oliver-oloughlin/kvdex/discussions/195

<div type='discussions-op-text'>

<sup>Originally posted by **ryanleecode** March 17, 2024</sup>
Is there any drawbacks to making the `idGenerator` async? For example I might want to use the web crypto api and do a sha256 hash to generate the id but that function is async.

`crypto.subtle.digest('SHA-256', ...)`</div>

**Comment by oliver-oloughlin** [comment]
This feature should now be implemented with version 0.35.3
