### ISSUE TITLE
Count not returning right value with filter option

### ISSUE THREAD

**Issue by danimrangelb** [oliver-oloughlin/kvdex#208]
I'm trying to count documents with a generic to calculate paginated results, the idea is to pass a field array to make it know where to search, in this case it is returning all the documents count instead of the filtered ones. The find operation does work as intended. 

This is my code:

```ts
import {
  Collection,
  CollectionOptions,
  Document,
  KvKey,
  KvValue,
} from "jsr:@olli/kvdex@1.0.1";

export interface PaginatedResults<T extends KvValue> {
  results: Document<T>[];
  total: number;
  totalPages: number;
  page: number;
}

interface Query<T> {
  page?: number;
  limit?: number;
  keyword?: string;
  fields?: Array<keyof T>;
  reverse?: boolean;
}

const filter = <T extends KvValue>(query: Query<T>, doc: Document<T>) =>
  !!query?.fields?.some((field) =>
    new RegExp(query.keyword!, "i").test(
      // @ts-ignore - this is a string
      (doc.value?.[field] as string) || ""
    )
  );

export const paginatedResults = async <T extends KvValue>(
  collection: Collection<unknown, T, CollectionOptions<T>>,
  query: Query<T> = {
    page: 1,
    limit: 10,
  }
): Promise<PaginatedResults<T>> => {
  const results = await collection.getMany({
    limit: query.limit,
    offset: query.page ? (query.page - 1) * query.limit! : 0,
    ...(query.keyword && {
      filter: (doc: Document<T>) => filter<T>(query, doc),
    }),
    ...(query.reverse && {
      reverse: true,
    }),
  });
  const total = await collection.count({
    ...(query.keyword && {
      filter: (doc: Document<T>) => filter<T>(query, doc),
    }),
  });
  const totalPages = Math.ceil(total / query.limit!);
  return {
    results: results.result,
    total,
    totalPages,
    page: query.page!,
  };
};
```

And this is an example of how to use it:

```ts
export const getLogs = async (query: {
  page?: number;
  limit?: number;
  keyword?: string;
}) => {
  return await paginatedResults<Logs>(db.logs, {
    ...query,
    reverse: true,
    fields: ["user", "printer"],
  });
};
```

Result screenshot: 

<img width="1440" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/142074688/e0fdcda7-b784-4327-a64e-3e6adacbd326">

In this case i'm looking matches on those fields against the keyword. Am I doing something wrong?

**Comment by oliver-oloughlin** [comment]
Hi, I tried running the code on my end. In the example you provided, I don't think you are passing the keyword along to the query? When I did the samme, I also got returned all documents. However, when I did provide a keyword matching only one of the documents, then I only got that single document returned. I also tried with a keyword that would match roughly half of the documents, and again I got the expected result of only that half. So to me it seems to be working as expected?

**Comment by danimrangelb** [comment]
@oliver-oloughlin I think I didn't explain myself well hahah, the results are as expected in all cases, what is wrong is the count operation, if you see in my example (screenshot) I am using a keyword that matches only 6 documents and that's ok, but the total returns 33. Is the count operation working well for you?

**Comment by oliver-oloughlin** [comment]
@danimrangelb For me it seems to be working, but I wonder if the difference in your case is due to the use of `limit` in the query and `getMany()` operation? If you want to do page pagination, you should probably use `resultLimit` instead. The difference is that `limit` directly corresponds to the native KV.list `limit` option, which limits the number of documents that are read from the database PRIOR to the filter function being applied. `resultLimit` limits the number of results which are returned AFTER the filter function is applied. Could this maybe explain the issue you are seeing? Also please keep in mind that page pagination is less efficient than cursor pagination, as it required more read operations.

**Comment by oliver-oloughlin** [comment]
Actually, let me amend my previous comment: You should probably use `resultLimit` for page pagination IF you are applying a filter as well (due to the reason explained above).

**Comment by danimrangelb** [comment]
@oliver-oloughlin Yup, it totally worked!! 
Maybe it should be documented btw, since I can see the JSDocs comments but it is not listed on the [jsr site](https://jsr.io/@olli/kvdex/doc/~/DenoKvListOptions):

<img width="914" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/142074688/9ea89e5e-73c3-4eae-8f23-d2703157710a">
<img width="634" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/142074688/5e3fe9e4-a2ae-4d93-84d8-c4a0ee80d1ba">


Thank you 😃 !!

**Comment by oliver-oloughlin** [comment]
Glad it worked!

The actual list options object is documented [here](https://jsr.io/@olli/kvdex@1.0.1/doc/~/ListOptions) (KvListOptions is a substitute type for the native KV list options, needed for compatibility reasons). But for some reason it doesn't show the comments until you click to see the code. So you are totally right, I should probably document this better and maybe add it to the README.
