### ISSUE TITLE
error: Selector can not specify both 'start' and 'end' key when specifying 'prefix'" when use getMany

### ISSUE THREAD

**Issue by Xu-pixel** [oliver-oloughlin/kvdex#251]
enviroment: bun 1.1.38 macos 15
i find that it cause by handlemany->createSelector
because denokv will check selector and forbidden use start ,end, prefix at the same time even if **undefined** 
https://github.com/denoland/denokv/blob/a9eb782be66477b32e96a692c8c34f807ad10bcd/npm/src/kv_util.ts#L115
![image](https://github.com/user-attachments/assets/d7a70e3f-fbe3-4f87-a937-8f73b883d43c)

**Comment by Xu-pixel** [comment]
![image](https://github.com/user-attachments/assets/f9e01a4b-83ae-4fa9-b493-ecf29f37a38b)
![image](https://github.com/user-attachments/assets/05b086af-6dc6-4900-bb46-b4bd57c36d05)

**Comment by oliver-oloughlin** [comment]
Weird quirk, but nicely done figuring it out! The change you made makes sense to me, if you care to make a PR I will gladly accept it :)

**Comment by Xu-pixel** [comment]
yes,i make a pr (#252 change the fn createListSelector) and test in deno(i don't how to test in bun)  although i think this is a problem with denokv, i can avoid it by modifying kvdex.
If you could merge this PR, I would be very grateful.

**Comment by oliver-oloughlin** [comment]
Closing this now as your fix has been merged and released as of 3.0.2. Thanks!
