### ISSUE TITLE
Possible error in KvValue type definition 

### ISSUE THREAD

**Issue by encendre** [oliver-oloughlin/kvdex#39]
Currently, in the file `src/types.ts`, `KvValue` is defined as

```ts
export type KvValue =
  | ...
  | Set<unknown>
  | Map<unknown, unknown>
  | ...
```

shouldn't it be defined as the following instead ? 

```ts
export type KvValue =
  | ...
  | Set<KvValue>
  | Map<KvValue, KvValue>
  | ...
```

Or maybe something more restrictive for the key of a `Map` ?

**Comment by oliver-oloughlin** [comment]
You are definitely right, thanks for pointing that out! After some quick testing, I think KvValue is restrictive enough for the map keys. I have updated the module (v0.6.1) with your suggested fix.
