### ISSUE TITLE
`Deno Lint: Type 'Element' is not assignable to type 'KvValue'.   Type 'VNode<any>' is not assignable to type 'KvObject'.     Index signature for type 'string' is missing in type 'VNode<any>'`

### ISSUE THREAD

**Issue by afifurrohman-id** [oliver-oloughlin/kvdex#42]
## Error:

```diff
Type 'Element' is not assignable to type 'KvValue'.
  Type 'VNode<any>' is not assignable to type 'KvObject'.
    Index signature for type 'string' is missing in type 'VNode<any>'
```
## Case
- error happen in component 
```tsx
<Element {...data}>
   <a
      href='/'
      className='font-bold active:opacity-100 hover:opacity-70 col-span-full'
    >
      <BsArrowLeft className='inline' /> Back Home
    </a>
</Element>
```
- **Fixed by remove `extends Model`**

```diff
export interface User 
-extends Model 
{
  readonly id: string
  name: string
  picture: string
  data: Data[]
}
```

**Comment by oliver-oloughlin** [comment]
Can I ask what type signature Data has? It seems like there is some field that doesn't conform to KvValue, which includes all values allowed to be stored in Deno KV.

**Comment by oliver-oloughlin** [comment]
Btw, the id field is already a part of a document. If you want to find users by id for example, you don't need to include the id as part of your model.

**Comment by afifurrohman-id** [comment]
> Can I ask what type signature Data has? It seems like there is some field that doesn't conform to KvValue, which includes all values allowed to be stored in Deno KV.

```ts
export interface Data {
  id: string
  title: string
  description: string
  createAt: number
  updateAt: number | null
  tags?: string[]
}
```

**Comment by afifurrohman-id** [comment]
> Btw, the id field is already a part of a document. If you want to find users by id for example, you don't need to include the id as part of your model.

Yes, but i want to using Google uID that received from oauth

**Comment by oliver-oloughlin** [comment]
Your model seems fine to me. But when I tried implementing it myself I received an error on the data field because the interface Data did not extend Model (KvObject). Have you tried letting the Data interface extend Model? Or simply use "type Data" instead of "interface Data"?

**Comment by afifurrohman-id** [comment]
Yeah my issues happen when i `extends Model`
So i remove

**Comment by oliver-oloughlin** [comment]
You fixed it by removing "extends Model"? But if you are still using an interface, I'm guessing it will now complain when trying to define a collection with the User interface? Or is everything ok? I would recommend still using "extends Model", but also doing it for every sub-type, like Data. Only necessary when using interfaces, not for types.

**Comment by afifurrohman-id** [comment]
> Your model seems fine to me. But when I tried implementing it myself I received an error on the data field because the interface Data did not extend Model (KvObject). Have you tried letting the Data interface extend Model? Or simply use "type Data" instead of "interface Data"?
> 
> ```ts
> interface Data extends Model {
>   id: string
>   title: string
>   description: string
>   createAt: number
>   updateAt: number | null
>   tags?: string[]
> }
> 
> // ..or
> type Data = {
>   ...
> }
> 
> interface User extends Model {
>   readonly id: string
>   name: string
>   picture: string
>   data: Data[]
> }
> ```

**okay now it's work**

change to type instead `interface`
