### ISSUE TITLE
0.18.5 breaks typing

### ISSUE THREAD

**Issue by J053Fabi0** [oliver-oloughlin/kvdex#96]
# 0.18.5
![image](https://github.com/oliver-oloughlin/kvdex/assets/12930717/6a82589d-8a86-434b-ac97-baf1f39d5ca0)

# 0.18.4
![image](https://github.com/oliver-oloughlin/kvdex/assets/12930717/c5378b63-7520-403c-8548-d441fb945732)

**Comment by oliver-oloughlin** [comment]
All the tests are passing for me. Have you tried re-caching your dependencies?

**Comment by oliver-oloughlin** [comment]
Before caching:
<img width="254" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/54100972/64cd44e1-454f-4465-a249-63ffc7e2f8b8">
<img width="762" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/54100972/b13ae9f3-809d-46f7-a3b3-cedc708ab7df">

After caching:

**Comment by oliver-oloughlin** [comment]
After updating and before caching:
<img width="799" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/54100972/dc185e78-9252-42a6-a1c8-3a847e6de3a4">
<img width="269" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/54100972/de18f411-a73c-4c89-b83e-246185eef2c5">

After caching:
<img width="338" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/54100972/0efbef3a-641d-49dd-8851-43555bfcefc1">
<img width="428" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/54100972/a4082fb3-042a-48ad-91dd-e30b98419a71">

**Comment by J053Fabi0** [comment]
It worked. Thank you. I guess Deno failed to cache it properly. I had to delete the cache directory.

**Comment by oliver-oloughlin** [comment]
Great to hear it worked! There is a setting for vscode you can add btw which helps with this by automatically caching dependencies of files upon saving.

<img width="299" alt="image" src="https://github.com/oliver-oloughlin/kvdex/assets/54100972/33ee167f-fc7e-4715-9c77-4ae751e2ab7e">
